package de.othr.sw.quickstart.dtos;

public enum Art {
    ZAHLUNGSEINGANG,
    NEUESEINKOMMEN,
    ZAHLUNGERFOLGREICH,
    ZAHLUNGABGELEHNT,
    BESCHAEFTIGUNGWECHSEL,
    KREDITAUFGENOMMEN,
    KREDITABBEZAHLT,
    KRYPTOKONTOERFOEFNET
}
